### PR TITLE
Replace private imports of TorchGeo models

### LINKED ISSUE #1031: Incompatible with torchgeo 0.8 due to unused ResNet import
**Describe the issue**
Terratorch 1.1.1 is incompatible with torchgeo 0.8 due to importing the ResNet class which was removed in torchgeo 0.8. The import occurs in
[terratorch/models/backbones/torchgeo_resnet.py:4](https://github.com/terrastackai/terratorch/blob/986f0a7e8d015bec10ad275c34a33188ffc0a19d/terratorch/models/backbones/torchgeo_resnet.py#L4). From what i can see the ResNet class is never used in the codebase - only the factory functions (resnet18, resnet50, resnet152) and weight classes are used.

**To Reproduce**

1. Install torchgeo 0.8: pip install torchgeo==0.8.0
2. Install terratorch: pip install terratorch==1.1.1
3. Try to import: from terratorch.tasks import SemanticSegmentationTask

<details><summary>Log Output</summary>
<pre>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 15
     13 import wandb
     14 from lightning.pytorch.loggers import WandbLogger
---> 15 from terratorch.tasks import SemanticSegmentationTask
     17 from src.data.datamodules.unet_change import SegmentationDataModule

File ~/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/terratorch/__init__.py:7
      4 import os
      5 os.environ["NO_ALBUMENTATIONS_UPDATE"] = "True"
----> 7 import terratorch.models  # noqa: F401
      8 from terratorch.models.backbones import *  # register models in registries # noqa: F403
      9 from terratorch.registry import BACKBONE_REGISTRY, DECODER_REGISTRY, MODEL_FACTORY_REGISTRY, FULL_MODEL_REGISTRY  # noqa: F401

File ~/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/terratorch/models/__init__.py:7
      4 import logging
      6 import terratorch.models.necks  # register necks  # noqa: F401
----> 7 from terratorch.models.clay1_5_model_factory import Clay1_5ModelFactory
      8 from terratorch.models.clay_model_factory import ClayModelFactory
      9 from terratorch.models.encoder_decoder_factory import EncoderDecoderFactory

File ~/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/terratorch/models/clay1_5_model_factory.py:12
      9 import logging
     11 import terratorch.models.decoders as decoder_registry
---> 12 from terratorch.models.backbones.clay_v1.embedder import Embedder
     13 from terratorch.models.model import (
     14     AuxiliaryHead,
     15     Model,
     16     ModelFactory,
     17 )
     18 from terratorch.models.pixel_wise_model import PixelWiseModel

File ~/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/terratorch/models/backbones/__init__.py:11
      9 import terratorch.models.backbones.scalemae
     10 import terratorch.models.backbones.terramind
---> 11 import terratorch.models.backbones.torchgeo_resnet
     12 import terratorch.models.backbones.torchgeo_swin_satlas
     13 import terratorch.models.backbones.torchgeo_vit

File ~/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/terratorch/models/backbones/torchgeo_resnet.py:4
      1 # reference torchgeo https://torchgeo.readthedocs.io/en/stable/_modules/torchgeo/models/resnet.html
      3 import torchgeo.models.resnet as resnet
----> 4 from torchgeo.models.resnet import ResNet, ResNet18_Weights, ResNet50_Weights, ResNet152_Weights, resnet18, resnet50, resnet152
      5 import logging
      6 from collections.abc import Callable

ImportError: cannot import name 'ResNet' from 'torchgeo.models.resnet' (/home/hkristen/miniforge3/envs/geoai-dev/lib/python3.11/site-packages/torchgeo/models/resnet.py)
</pre>
</details>

**Expected behavior**

Terratorch should work with torchgeo 0.8.

**Deployment information**

- TerraTorch version: 1.1.1
- Installation source: pip
- torchgeo version: 0.8.0 (attempting to use; currently constrained to <0.7.2)

FYI @adamjstewart

### PR DESCRIPTION
**Pull request by adamjstewart**
Things like `torchgeo.models.resnet` are not documented and considered an implementation detail. Only the top-level `torchgeo.models` API is public.

Fixes #1031

### CODE REVIEW

**Comment by adamjstewart** [comment]
There are a bunch of similar inputs for datasets/datamodules that should also be fixed:
```console
> git grep 'from torchgeo\..*\.'
terratorch/datamodules/geobench_v2_data_module.py:from torchgeo.datasets.utils import lazy_import, percentile_normalization
terratorch/datamodules/m_VHR10.py:from torchgeo.datasets.utils import (
terratorch/datamodules/substation.py:from torchgeo.datasets.utils import (
terratorch/datasets/biomassters.py:from torchgeo.datasets.utils import percentile_normalization
terratorch/datasets/generic_scalar_label_dataset.py:from torchgeo.datasets.utils import rasterio_loader
terratorch/datasets/m_VHR10.py:from torchgeo.datasets.utils import (
terratorch/datasets/substation.py:from torchgeo.datasets.errors import DatasetNotFoundError
terratorch/datasets/substation.py:from torchgeo.datasets.geo import NonGeoDataset
terratorch/datasets/substation.py:from torchgeo.datasets.utils import Path, download_url, extract_archive
terratorch/tasks/base_task.py:from torchgeo.datasets.utils import unbind_samples
terratorch/tasks/classification_tasks.py:from torchgeo.datasets.utils import unbind_samples
terratorch/tasks/inference_task.py:from torchgeo.datasets.utils import unbind_samples
terratorch/tasks/reconstruction_tasks.py:from torchgeo.datasets.utils import unbind_samples
terratorch/tasks/regression_tasks.py:from torchgeo.datasets.utils import unbind_samples
terratorch/tasks/segmentation_tasks.py:from torchgeo.datasets.utils import unbind_samples
terratorch/vllm/plugins/__init__.py:from torchgeo.datamodules.geo import BaseDataModule
tests/datamodules/test_sen1floods11.py:from torchgeo.datasets.utils import unbind_samples
tests/test_substation.py:from torchgeo.datasets.errors import DatasetNotFoundError
```
Some of these are available in torchgeo.datasets and some aren't.

**Review by romeokienzler — APPROVED** [review]
